import axios from "axios";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default async function Home() {
  const { data } = await axios.post(
    "https://a2a-api.klipwallet.com/v2/a2a/prepare",
    {
      bapp: {
        name: "test",
        callback: {
          success: "test://",
          fail: "test://",
        },
      },
      type: "auth",
    }
  );
  console.log(data);
  const { data: res, status } = await axios.get(
    "https://a2a-api.klipwallet.com/v2/a2a/result?request_key=" +
      data.request_key
  );
  console.log(res);
  console.log(status);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hi</div>
    </div>
  );
}
